name: charliechang
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pin_input_text_field: ^3.0.1
  smooth_star_rating: ^1.1.1
  #getflutter: ^1.0.11
  http: ^0.12.0+3
  progress_dialog: ^1.2.2
  fluttertoast: ^4.0.1
  connectivity: ^0.4.8+2
  shared_preferences: 0.5.3+1
  intl: ^0.16.1
  #dio: ^3.0.9
  flutter_svg: ^0.17.4
  badges: ^1.1.1
  bloc_pattern:
  rxdart:
  provider: ^3.0.0
#  flutter_webview_plugin: ^0.3.11
  flutter_webview_plugin: ^0.3.9

  #maps_launcher: ^1.2.1
  url_launcher: ^5.4.0
  firebase_messaging: ^6.0.16
  flutter_share: ^1.0.2+1
  sticky_headers: ^0.1.7
  scroll_to_index: ^1.0.6
  pinput: ^0.2.4
  extended_nested_scroll_view: ^1.0.1
  loading_more_list: ^3.0.0
  pin_code_fields: ^4.0.0
  flutter_staggered_grid_view: ^0.3.2
  store_redirect: ^1.0.2
  getwidget: ^1.1.3
  flutter_local_notifications: ^1.4.4+4
  marquee: ^1.6.1
  carousel_pro: ^1.0.0
  firebase_crashlytics: ^0.2.1+1
  firebase_core: ^0.5.0+1
  cached_network_image: ^2.2.0
  flutter_image: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_bg.png
    - assets/images/splash_img.png
    - assets/images/reg_img.png
    - assets/images/forword_arrow.png
    - assets/images/otp_img.png
    - assets/images/cc_specials.png
    - assets/images/dish1.png
    - assets/images/dish2.png
    - assets/images/dish3.png
    - assets/images/dish4.png
    - assets/images/dish5.png
    - assets/images/cart.png
    - assets/images/offers.png
    - assets/images/updates.png
    - assets/images/more.png
    - assets/images/home.png
    - assets/images/profile.png
    - assets/images/about.png
    - assets/images/logout.png
    - assets/images/points.png
    - assets/images/support.png
    - assets/images/next.png
    - assets/images/refer.png
    - assets/images/address.png
    - assets/images/password.png
    - assets/images/refer_img.png
    - assets/images/copy.png
    - assets/images/upload.png
    - assets/images/image.png
    - assets/images/image2.png
    - assets/images/thanks_img.png
    - assets/images/spalsh_bg.png
    - assets/images/logo.png
    - assets/images/otp_image.jpg
    - assets/images/loading.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope_Bold.otf
        - asset: assets/fonts/Manrope_Regular.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.otf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
